name: Deploy to Pratham-QA Server
on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
   
      - name: Show PWD
        run: |
           echo "Current Working Directory:"
           pwd
      - name: List Contents
        run: |
           echo "Contents of the current directory (in reverse order):"
            ls -lr
      - name: List Contents
        run: |
           echo "Contents of the dist directory (in reverse order):"
            pwd
            
            ls -lr

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_PRATHAM_QA }}
          REMOTE_HOST: ${{ secrets.HOST_NAME_PRATHAM_QA }}
          REMOTE_USER: ${{ secrets.USERNAME_PRATHAM_QA }}
          TARGET: ${{ secrets.TARGET_DIR_PRATHAM_QA }}

      - name: Set up SSH key
        run: | 
         mkdir -p ~/.ssh
         echo "${{ secrets.EC2_SSH_KEY_PRATHAM_QA }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         # Add the SSH key to the known_hosts file (replace hostname with your actual hostname)
         ssh-keyscan -H ${{ secrets.HOST_NAME_PRATHAM_QA }} >> ~/.ssh/known_hosts
    
      - name: Unzip Artifact to Correct Locations to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PRATHAM_QA }}
          username: ${{ secrets.USERNAME_PRATHAM_QA }}
          key: ${{ secrets.EC2_SSH_KEY_PRATHAM_QA }}
          local: "/home/runner/work/shiksha-components/shiksha-components/dist/" 
          remote: "/var/www/qa.prathamteacherapp.tekdinext.com/public"